name: CI
on: 
  pull_request:
    branches: 
    - master

jobs:
  "Compile":
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Compile
      run: |
        cd compile
        ./build.sh
